version: '3.8'

services:

  assignit_backend:
    image: node:20
    container_name: assignit_backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3092:8081
    depends_on:
      - assignit_db
    command: ["npm", "start"]

  assignit_db:
    image: postgres:latest
    container_name: assignit_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AssignitPass123
      - POSTGRES_DB=assignit
    volumes:
      - assignit_postgres_data:/var/lib/postgresql
    ports:
      - 7898:5432

volumes:
  assignit_postgres_data:
    driver: local
